name: API Workflow

on:
  pull_request:
    branches: [main]
    paths:
      - "**/abc-store-api/**"
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Test with coverage

    defaults:
      run:
        working-directory: ./abc-store-api

    env:
      SONAR_PROJECT_KEY: abc-store-api
      SONAR_ORG: themegat
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Restore Tools
        run: dotnet tool restore

      - name: SonarCloud - Begin analysis
        run: >
          dotnet sonarscanner begin \
          -k:"$SONAR_PROJECT_KEY" \
          -o:"$SONAR_ORG" \
          -d:sonar.login="$SONAR_TOKEN" \
          -d:sonar.coverageReportPaths="Coverage/SonarQube.xml" \
          -d:sonar.qualitygate.wait=true

      - name: Test
        run: dotnet test --collect:"Code Coverage" --settings:.runsettings

      - name: Generate SonarQube coverage report
        run: |
          dotnet reportgenerator \
            -reports:./Coverage/**/*.cobertura.xml \
            -targetdir:./Coverage/ \
            -reporttypes:SonarQube

      - name: SonarCloud - End analysis
        run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: /**/Coverage/**/*.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "40 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
